Import('env')

for source in Glob('*.c'):
    test = env.Program(
        str(source).rstrip('.c'),
        [source],
        LIBPATH='../../',
        LIBS=['beemo', 'm', 'pthread', 'lua5.2', 'portaudio'],
        CCFLAGS=env['CCFLAGS']+['-g3']
    )
