language: c
sudo: false
env:
  - RELEASE='--enable=release'
  - RELEASE=''
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - valgrind
      - portaudio19-dev
      - libjack-dev
      - ladspa-sdk
      - liblua5.2-dev
      - libsndfile1-dev
      - lua5.2
      - alsa-utils
script: source tests/activate && scons tests $RELEASE
